# Generated by Django 3.0.4 on 2020-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('compulsory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('student_name', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('adm_no', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('kcpe', models.IntegerField(null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('form', models.IntegerField()),
                ('stream', models.CharField(max_length=1)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('parent_phone_number', models.CharField(max_length=20, null=True)),
                ('guardian_phone', models.CharField(max_length=20, null=True)),
                ('parent_name', models.CharField(max_length=30, null=True)),
                ('guardian_name', models.CharField(max_length=30, null=True)),
                ('county', models.CharField(max_length=30, null=True)),
                ('birth_cert', models.IntegerField(null=True)),
                ('adm_date', models.DateField(null=True)),
                ('upi_no', models.CharField(max_length=40, null=True)),
                ('form1_term1_bot', models.TextField(blank=True, null=True)),
                ('form1_term1_mot', models.TextField(blank=True, null=True)),
                ('form1_term1_eot', models.TextField(blank=True, null=True)),
                ('form1_term2_bot', models.TextField(blank=True, null=True)),
                ('form1_term2_mot', models.TextField(blank=True, null=True)),
                ('form1_term2_eot', models.TextField(blank=True, null=True)),
                ('form1_term3_bot', models.TextField(blank=True, null=True)),
                ('form1_term3_mot', models.TextField(blank=True, null=True)),
                ('form1_term3_eot', models.TextField(blank=True, null=True)),
                ('form2_term1_bot', models.TextField(blank=True, null=True)),
                ('form2_term1_mot', models.TextField(blank=True, null=True)),
                ('form2_term1_eot', models.TextField(blank=True, null=True)),
                ('form2_term2_bot', models.TextField(blank=True, null=True)),
                ('form2_term2_mot', models.TextField(blank=True, null=True)),
                ('form2_term2_eot', models.TextField(blank=True, null=True)),
                ('form2_term3_bot', models.TextField(blank=True, null=True)),
                ('form2_term3_mot', models.TextField(blank=True, null=True)),
                ('form2_term3_eot', models.TextField(blank=True, null=True)),
                ('form3_term1_bot', models.TextField(blank=True, null=True)),
                ('form3_term1_mot', models.TextField(blank=True, null=True)),
                ('form3_term1_eot', models.TextField(blank=True, null=True)),
                ('form3_term2_bot', models.TextField(blank=True, null=True)),
                ('form3_term2_mot', models.TextField(blank=True, null=True)),
                ('form3_term2_eot', models.TextField(blank=True, null=True)),
                ('form3_term3_bot', models.TextField(blank=True, null=True)),
                ('form3_term3_mot', models.TextField(blank=True, null=True)),
                ('form3_term3_eot', models.TextField(blank=True, null=True)),
                ('form4_term1_bot', models.TextField(blank=True, null=True)),
                ('form4_term1_mot', models.TextField(blank=True, null=True)),
                ('form4_term1_eot', models.TextField(blank=True, null=True)),
                ('form4_term2_bot', models.TextField(blank=True, null=True)),
                ('form4_term2_mot', models.TextField(blank=True, null=True)),
                ('form4_term2_eot', models.TextField(blank=True, null=True)),
                ('form4_term3_bot', models.TextField(blank=True, null=True)),
                ('form4_term3_mot', models.TextField(blank=True, null=True)),
                ('form4_term3_eot', models.TextField(blank=True, null=True)),
                ('subjects', models.ManyToManyField(to='schoolapp.Subject')),
            ],
        ),
    ]
