# Generated by Django 3.0.4 on 2020-03-11 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1bot', models.BooleanField()),
                ('term2bot', models.BooleanField()),
                ('term3bot', models.BooleanField()),
                ('term1mot', models.BooleanField()),
                ('term2mot', models.BooleanField()),
                ('term3mot', models.BooleanField()),
                ('term1eot', models.BooleanField()),
                ('term2eot', models.BooleanField()),
                ('term3eot', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.ManyToManyField(to='schoolapp.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
