# Generated by Django 3.0.4 on 2020-03-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_portal_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='selected_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='selected_stream',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='selected_subject',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
