# Generated by Django 3.0.4 on 2020-03-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20200311_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='selected_form',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='selected_stream',
        ),
        migrations.AddField(
            model_name='teacher',
            name='selected_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
