# Generated by Django 3.0.4 on 2020-03-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_auto_20200311_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='form2_term3_bot',
            new_name='form2_term3bot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form2_term3_eot',
            new_name='form2_term3eot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form2_term3_mot',
            new_name='form2_term3mot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term1_bot',
            new_name='form3_term1bot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term1_eot',
            new_name='form3_term1eot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term1_mot',
            new_name='form3_term1mot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term2_bot',
            new_name='form3_term2bot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term2_eot',
            new_name='form3_term2eot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term2_mot',
            new_name='form3_term2mot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term3_bot',
            new_name='form3_term3bot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term3_eot',
            new_name='form3_term3eot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form3_term3_mot',
            new_name='form3_term3mot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form4_term1_bot',
            new_name='form4_term1bot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form4_term1_eot',
            new_name='form4_term1eot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form4_term1_mot',
            new_name='form4_term1mot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form4_term2_bot',
            new_name='form4_term2bot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form4_term2_eot',
            new_name='form4_term2eot',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='form4_term2_mot',
            new_name='form4_term2mot',
        ),
    ]
