# Generated by Django 3.0.4 on 2020-03-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20200311_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGradingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField(blank=True, null=True)),
                ('Aplain_upper', models.IntegerField()),
                ('Aplain_lower', models.IntegerField()),
                ('Aplain_points', models.IntegerField()),
                ('Aminus_upper', models.IntegerField()),
                ('Aminus_lower', models.IntegerField()),
                ('Aminus_points', models.IntegerField()),
                ('Bplus_upper', models.IntegerField()),
                ('Bplus_lower', models.IntegerField()),
                ('Bplus_points', models.IntegerField()),
                ('Bplain_upper', models.IntegerField()),
                ('Bplain_lower', models.IntegerField()),
                ('Bplain_points', models.IntegerField()),
                ('Bminus_upper', models.IntegerField()),
                ('Bminus_lower', models.IntegerField()),
                ('Bminus_points', models.IntegerField()),
                ('Cplus_upper', models.IntegerField()),
                ('Cplus_lower', models.IntegerField()),
                ('Cplus_points', models.IntegerField()),
                ('Cplain_upper', models.IntegerField()),
                ('Cplain_lower', models.IntegerField()),
                ('Cplain_points', models.IntegerField()),
                ('Cminus_upper', models.IntegerField()),
                ('Cminus_lower', models.IntegerField()),
                ('Cminus_points', models.IntegerField()),
                ('Dplus_upper', models.IntegerField()),
                ('Dplus_lower', models.IntegerField()),
                ('Dplus_points', models.IntegerField()),
                ('Dplain_upper', models.IntegerField()),
                ('Dplain_lower', models.IntegerField()),
                ('Dplain_points', models.IntegerField()),
                ('Dminus_upper', models.IntegerField()),
                ('Dminus_lower', models.IntegerField()),
                ('Dminus_points', models.IntegerField()),
                ('Eplain_upper', models.IntegerField()),
                ('Eplain_lower', models.IntegerField()),
                ('Eplain_points', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Subject')),
            ],
        ),
    ]
