# Generated by Django 3.0.4 on 2020-03-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_auto_20200312_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kcpe_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
