# Generated by Django 3.0.4 on 2020-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_student_kcpe_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.TextField(blank=True, null=True)),
                ('adm_no', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('kcpe', models.IntegerField(blank=True, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('form', models.IntegerField()),
                ('stream', models.CharField(max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=30, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_cert', models.IntegerField(blank=True, null=True)),
                ('adm_date', models.TextField(blank=True, null=True)),
                ('upi_no', models.CharField(blank=True, max_length=40, null=True)),
                ('kcpe_index', models.IntegerField(blank=True, null=True)),
                ('form1_term1bot', models.TextField(blank=True, null=True)),
                ('form1_term1mot', models.TextField(blank=True, null=True)),
                ('form1_term1eot', models.TextField(blank=True, null=True)),
                ('form1_term2bot', models.TextField(blank=True, null=True)),
                ('form1_term2mot', models.TextField(blank=True, null=True)),
                ('form1_term2eot', models.TextField(blank=True, null=True)),
                ('form1_term3bot', models.TextField(blank=True, null=True)),
                ('form1_term3mot', models.TextField(blank=True, null=True)),
                ('form1_term3eot', models.TextField(blank=True, null=True)),
                ('form2_term1bot', models.TextField(blank=True, null=True)),
                ('form2_term1mot', models.TextField(blank=True, null=True)),
                ('form2_term1eot', models.TextField(blank=True, null=True)),
                ('form2_term2bot', models.TextField(blank=True, null=True)),
                ('form2_term2mot', models.TextField(blank=True, null=True)),
                ('form2_term2eot', models.TextField(blank=True, null=True)),
                ('form2_term3bot', models.TextField(blank=True, null=True)),
                ('form2_term3mot', models.TextField(blank=True, null=True)),
                ('form2_term3eot', models.TextField(blank=True, null=True)),
                ('form3_term1bot', models.TextField(blank=True, null=True)),
                ('form3_term1mot', models.TextField(blank=True, null=True)),
                ('form3_term1eot', models.TextField(blank=True, null=True)),
                ('form3_term2bot', models.TextField(blank=True, null=True)),
                ('form3_term2mot', models.TextField(blank=True, null=True)),
                ('form3_term2eot', models.TextField(blank=True, null=True)),
                ('form3_term3bot', models.TextField(blank=True, null=True)),
                ('form3_term3mot', models.TextField(blank=True, null=True)),
                ('form3_term3eot', models.TextField(blank=True, null=True)),
                ('form4_term1bot', models.TextField(blank=True, null=True)),
                ('form4_term1mot', models.TextField(blank=True, null=True)),
                ('form4_term1eot', models.TextField(blank=True, null=True)),
                ('form4_term2bot', models.TextField(blank=True, null=True)),
                ('form4_term2mot', models.TextField(blank=True, null=True)),
                ('form4_term2eot', models.TextField(blank=True, null=True)),
                ('form4_term3bot', models.TextField(blank=True, null=True)),
                ('form4_term3mot', models.TextField(blank=True, null=True)),
                ('form4_term3eot', models.TextField(blank=True, null=True)),
                ('subjects', models.ManyToManyField(to='schoolapp.Subject')),
            ],
        ),
    ]
