# Generated by Django 3.0.4 on 2020-03-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_auto_20200313_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='form4term1_closing_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='form4term2_closing_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='form4term3_closing_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
