# Generated by Django 3.0.4 on 2020-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_auto_20200313_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='initials',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
