# Generated by Django 3.0.4 on 2020-03-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0018_auto_20200313_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('adm_no', 'student_name')},
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
