# Generated by Django 3.0.4 on 2020-03-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0019_auto_20200314_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Teacher'),
        ),
    ]
