# Generated by Django 3.0.4 on 2020-03-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0020_auto_20200314_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
