# Generated by Django 3.0.4 on 2020-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0021_auto_20200314_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_and_closing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField()),
                ('opening_date', models.DateField()),
            ],
        ),
    ]
