# Generated by Django 3.0.4 on 2020-03-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0022_open_and_closing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_and_closing',
            name='closing_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='open_and_closing',
            name='opening_date',
            field=models.TextField(),
        ),
    ]
