# Generated by Django 3.0.4 on 2020-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_fee_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feestructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.IntegerField()),
                ('term2', models.IntegerField()),
                ('term3', models.IntegerField()),
                ('term4', models.IntegerField()),
            ],
        ),
    ]
