# Generated by Django 3.0.4 on 2020-03-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feestructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='term4',
        ),
    ]
